import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "../components/NavBar";
import Footer from "../components/Footer";
import getSiteConfig from "./api/siteConfig";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Garage B",
  description: "Generated by TheGym",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data } = await getSiteConfig();
  const { footer, navbar } = data;
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href={navbar.favicon.url}
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href={navbar.favicon.url}
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href={navbar.favicon.url}
        />
      </head>
      <body
        className={`${montserrat.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <Navbar {...navbar} />
        {children}
        <Footer {...footer} />
      </body>
    </html>
  );
}
